// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIw7cv_LblELFTL0yLPfD4MKl4Z-xJwa8',
    appId: '1:155852623216:web:2ea6777ecf1cfe857d93b5',
    messagingSenderId: '155852623216',
    projectId: 'finlit-app-b0faf',
    authDomain: 'finlit-app-b0faf.firebaseapp.com',
    storageBucket: 'finlit-app-b0faf.firebasestorage.app',
    measurementId: 'G-YR8YEH7P64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_9terk-6bGcPp6XC4C94RN_ELBzLICG4',
    appId: '1:155852623216:android:f1836939ddebbcb37d93b5',
    messagingSenderId: '155852623216',
    projectId: 'finlit-app-b0faf',
    storageBucket: 'finlit-app-b0faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfWCOawW1PY5h_Vbw83EHR2Ak-ddY2Xw4',
    appId: '1:155852623216:ios:1f2a0d902d1257bb7d93b5',
    messagingSenderId: '155852623216',
    projectId: 'finlit-app-b0faf',
    storageBucket: 'finlit-app-b0faf.firebasestorage.app',
    iosBundleId: 'com.example.projectName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfWCOawW1PY5h_Vbw83EHR2Ak-ddY2Xw4',
    appId: '1:155852623216:ios:1f2a0d902d1257bb7d93b5',
    messagingSenderId: '155852623216',
    projectId: 'finlit-app-b0faf',
    storageBucket: 'finlit-app-b0faf.firebasestorage.app',
    iosBundleId: 'com.example.projectName',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIw7cv_LblELFTL0yLPfD4MKl4Z-xJwa8',
    appId: '1:155852623216:web:2991018e7b3f87177d93b5',
    messagingSenderId: '155852623216',
    projectId: 'finlit-app-b0faf',
    authDomain: 'finlit-app-b0faf.firebaseapp.com',
    storageBucket: 'finlit-app-b0faf.firebasestorage.app',
    measurementId: 'G-SZV4NZBC8C',
  );
}
